version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: hask_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
